version: '3.8'

services:
  # Next.js Application
  dahab-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dahab-tablet-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Firebase configuration - replace with your actual values
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
    volumes:
      # Mount .env file for environment variables
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - dahab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (alternative for development)
  dahab-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dahab-tablet-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - dahab-network
    profiles:
      - dev # Only runs when explicitly specified

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: dahab-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # For SSL certificates
    depends_on:
      - dahab-app
    restart: unless-stopped
    networks:
      - dahab-network
    profiles:
      - production # Only runs in production profile

networks:
  dahab-network:
    driver: bridge
    name: dahab-tablet-network

volumes:
  node_modules:
    name: dahab-node-modules
