# Docker Compose override for development environment
version: '3.8'

services:
  dahab-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # For file watching in Docker
    command: pnpm dev
